### ISSUE TITLE
Inclusion of the tree <div> interferes with remainder of page

### ISSUE THREAD

**Issue by mflanagan** [dipson88/treeselectjs#11]
I have a page at http://www.mjflanagan.com/LengthsCounter.html. I then add the TreeSelect code as a div after the "main" div; that modified page is here: http://www.mjflanagan.com/LengthsAndDq/index.html (Both of these pages are "complete." That is, there's no web server rendering anything. You can download the files and inspect them, of course.)

It appears that the "bottom" of the new page (with TreeSelect), starting below the table, is being overlaid by the TreeSelect. You can see in the following image that I've selected one of the elements that's being cut off; you can see it underlying the tree select.

(Sorry if it's something in my HTML is screwing this up.)

![image](https://user-images.githubusercontent.com/453757/176286075-0117c173-f41e-483e-ab64-d21283f8e543.png)

**Comment by dipson88** [comment]
I see. Initially, when I was developing the component, I thought developers will use alwaysOpen prop for debugging or something like that =). The list has an absolute position; it leads to the overlapping.
The fast solution for you will be set alwaysOpen to false. It will lead to a hiding list in a blur as a regular dropdown. In the next release, I will try to add a prop, or change behavior for alwaysOpen prop. List will become as a static part of the DOM instead of absolute, but it means that list will render in the bottom mode, or I can add a prop for the force direction as well.

**Comment by mflanagan** [comment]
Thanks. How do I get it to open, then?

**Comment by mflanagan** [comment]
Ahhh; I see. Sorry. Now `alwaysOpen` makes sense to me. Thanks.

**Comment by mflanagan** [comment]
No, it makes sense. I don't use html/css very often; I'm mostly a back-end coder (node, express, REST, etc.). So when I dabble, as with this little app I'm using the Tree for, I have to re-immerse myself in html and the lingo. Of course when we're talking about a dropdown, "open" makes sense. I'd keep the name; the shortcoming is me!

**Comment by dipson88** [comment]
@mflanagan, I added `staticList` prop in new v0.2.7, you also can check `README`. Now if you what to use the list as a default DOM element without overlapping and absolute position you can use this prop. Do not use `appendToBody` with this parameter, you will see a console error, `appendToBody` uses only as an absolute element. But in your case, you don't need this. I added an info to the `README` about it..

**Comment by mflanagan** [comment]
Perfect; thanks!
